[keys]
prefix = "ctrl+t"

new_tab = ["prefix+c", "prefix+ctrl+c"]
new_workspace = "prefix+shift+c"
previous_tab = ["prefix+p", "prefix+ctrl+p"]
next_tab = ["prefix+n", "prefix+ctrl+n"]

split_horizontal = ["prefix+minus", "prefix+2"]
split_vertical = ["prefix+v", "prefix+3"]

detach = ["prefix+q", "prefix+d", "prefix+ctrl+d"]
rename_tab = ["prefix+shift+t", "prefix+shift+a"]

[ui]
prompt_new_tab_name = false
