gui:
  wrapLinesInStagingView: true
git:
  diffRenderers:
    - command: delta --paging=never --max-line-length=0
keybinding:
  universal:
    return: [<esc>, <ctrl+g>]
    prevItem: [<up>, <ctrl+p>]
    nextItem: [<down>, <ctrl+n>]
    prevPage: [',', <ctrl+meta+v>]
    nextPage: ['.', <ctrl+v>]
    createPatchOptionsMenu: <disabled>
